type Document = { title: string; intro: string; backLabel: string; sections: { heading: string; paragraphs: string[] }[] };
const email = "support@web-reflect.com";

const en = {
  privacy: { title: "Privacy Policy", intro: "This policy explains what personal information Web Reflect collects, why we use it, and the choices available to you. Last updated: September 12, 2026.", backLabel: "Back to Web Reflect", sections: [
    { heading: "Information we collect", paragraphs: ["When you contact us by email, telephone, or WhatsApp, we may receive information you choose to provide, such as your name, contact details, company details, and the contents of your enquiry.", "Hosting and technical providers may process limited technical data needed to operate and secure the website, including IP address, browser and device information, requested pages, and request time. We do not use advertising pixels, analytics trackers, or account registration.", "When you choose an accessibility setting, such as text size, high contrast, or underlined links, we store that preference only in your browser's local storage so it can be remembered on later visits. This preference is not used for advertising or visitor tracking."] },
    { heading: "How we use and share information", paragraphs: ["We use information to respond to enquiries, provide requested services, manage business communications, protect the website, and meet legal obligations. We do not sell personal information or use it for unrelated advertising.", "We share information only where necessary to provide services, operate and secure the site, comply with law, or protect our rights. WhatsApp communications are also subject to WhatsApp's privacy practices."] },
    { heading: "Retention, security, and deletion", paragraphs: ["We retain information only as long as reasonably needed or legally required and use reasonable safeguards to protect it. No internet transmission or storage system is completely secure.", `You may request access, correction, or deletion by emailing ${email} with the subject Data deletion request. Include enough information to identify your request. We will respond under applicable law; some data may need to be retained where permitted or required.`] },
    { heading: "Changes and contact", paragraphs: [`We may update this policy when our practices or legal requirements change. The latest version will be posted here. Privacy questions: ${email}.`] },
  ] },
  terms: { title: "Terms of Use", intro: "These terms govern your use of the Web Reflect website. Last updated: September 12, 2026.", backLabel: "Back to Web Reflect", sections: [
    { heading: "Using this website", paragraphs: ["Use this website only for lawful personal or business purposes. Do not interfere with its operation, attempt unauthorized access, introduce harmful code, or use its content in a way that infringes the rights of Web Reflect or others."] },
    { heading: "Website content and enquiries", paragraphs: ["Unless stated otherwise, this website's design, text, graphics, logos, and other content are owned by or licensed to Web Reflect. You may not copy, modify, distribute, or use them commercially without written permission.", "Information on this site is general information and does not create a contractual relationship. Services, scope, timing, fees, and deliverables must be agreed in a separate written agreement."] },
    { heading: "External links, disclaimer, and changes", paragraphs: ["Third-party services, including WhatsApp, are independent of Web Reflect. We are not responsible for their content, availability, or privacy practices.", "The website is provided as is and as available to the extent permitted by law. We may change these terms or the website at any time. Questions: support@web-reflect.com."] },
  ] },
} satisfies { privacy: Document; terms: Document };

const he = {
  privacy: { title: "מדיניות פרטיות", intro: "מדיניות זו מסבירה איזה מידע אישי Web Reflect אוספת, מדוע אנו משתמשים בו ואילו אפשרויות עומדות לרשותכם. עודכן לאחרונה: 12 בספטמבר 2026.", backLabel: "חזרה ל-Web Reflect", sections: [
    { heading: "המידע שאנו אוספים", paragraphs: ["כאשר אתם יוצרים קשר בדוא״ל, בטלפון או ב-WhatsApp, אנו עשויים לקבל מידע שתבחרו למסור, כגון שם, פרטי התקשרות, פרטי חברה ותוכן הפנייה.", "ספקי אחסון וטכנולוגיה עשויים לעבד מידע טכני מוגבל הנדרש להפעלה ולאבטחת האתר, כגון כתובת IP, מידע על הדפדפן והמכשיר, דפים שהתבקשו ומועד הבקשה. איננו משתמשים בפיקסלים פרסומיים, מעקב אנליטי או רישום חשבונות.", "כאשר אתם בוחרים הגדרות נגישות, כגון גודל טקסט, ניגודיות גבוהה או קווים תחת קישורים, אנו שומרים את ההעדפה רק באחסון המקומי בדפדפן כדי לזכור אותה בביקורים הבאים. ההעדפה אינה משמשת לפרסום או למעקב אחר מבקרים."] },
    { heading: "שימוש ושיתוף במידע", paragraphs: ["אנו משתמשים במידע כדי להשיב לפניות, לספק שירותים שהתבקשו, לנהל תקשורת עסקית, להגן על האתר ולעמוד בחובות חוקיות. איננו מוכרים מידע אישי ואיננו משתמשים בו לפרסום שאינו קשור לפנייה.", "מידע משותף רק כשנדרש למתן שירות, להפעלת האתר ולאבטחתו, לעמידה בחוק או להגנה על זכויותינו. שיחות WhatsApp כפופות גם למדיניות הפרטיות של WhatsApp."] },
    { heading: "שמירה, אבטחה ומחיקת מידע", paragraphs: ["אנו שומרים מידע רק למשך הזמן הנדרש באופן סביר או לפי חוק, ונוקטים אמצעי הגנה סבירים. שום העברה או אחסון באינטרנט אינם מאובטחים לחלוטין.", `ניתן לבקש גישה, תיקון או מחיקה באמצעות דוא״ל אל ${email} עם הנושא בקשת מחיקת מידע. יש לכלול פרטים מספיקים לזיהוי הבקשה. נשיב לפי הדין החל; מידע מסוים עשוי להישמר כאשר הדבר נדרש או מותר בחוק.`] },
    { heading: "שינויים ויצירת קשר", paragraphs: [`אנו עשויים לעדכן מדיניות זו. הגרסה העדכנית תפורסם כאן. לשאלות בנושא פרטיות: ${email}.`] },
  ] },
  terms: { title: "תנאי שימוש", intro: "תנאים אלה מסדירים את השימוש שלכם באתר Web Reflect. עודכן לאחרונה: 12 בספטמבר 2026.", backLabel: "חזרה ל-Web Reflect", sections: [
    { heading: "שימוש באתר", paragraphs: ["ניתן להשתמש באתר למטרות חוקיות, אישיות או עסקיות. אין להפריע לפעילותו, לנסות גישה בלתי מורשית, להחדיר קוד מזיק או להשתמש בתוכן באופן הפוגע בזכויות של Web Reflect או אחרים."] },
    { heading: "תוכן האתר ופניות", paragraphs: ["אלא אם צוין אחרת, העיצוב, הטקסטים, הגרפיקה, הסמלים ותכנים אחרים באתר הם בבעלות Web Reflect או בשימושה. אין להעתיק, לשנות, להפיץ או להשתמש בהם מסחרית ללא אישור בכתב.", "המידע באתר הוא כללי ואינו יוצר קשר חוזי. שירותים, היקף, מועדים, מחירים ותוצרים יוסכמו בהסכם כתוב נפרד."] },
    { heading: "קישורים חיצוניים ושינויים", paragraphs: ["שירותי צד שלישי, לרבות WhatsApp, הם עצמאיים ואיננו אחראים לתוכן, לזמינות או למדיניות הפרטיות שלהם.", `האתר מסופק כפי שהוא ובכפוף לזמינותו. אנו רשאים לשנות תנאים אלה או את האתר בכל עת. שאלות: ${email}.`] },
  ] },
} satisfies { privacy: Document; terms: Document };

const ar = {
  privacy: { title: "سياسة الخصوصية", intro: "تشرح هذه السياسة المعلومات الشخصية التي تجمعها Web Reflect، وسبب استخدامها، والخيارات المتاحة لكم. آخر تحديث: 12 سبتمبر 2026.", backLabel: "العودة إلى Web Reflect", sections: [
    { heading: "المعلومات التي نجمعها", paragraphs: ["عند التواصل معنا عبر البريد الإلكتروني أو الهاتف أو WhatsApp، قد نتلقى المعلومات التي تختارون تقديمها، مثل الاسم وبيانات الاتصال والشركة ومحتوى الاستفسار.", "قد يعالج مزودو الاستضافة والخدمات التقنية معلومات محدودة لتشغيل الموقع وحمايته، مثل عنوان IP ومعلومات المتصفح والجهاز والصفحات المطلوبة ووقت الطلب. لا نستخدم بكسلات إعلانية أو أدوات تتبع تحليلية أو تسجيل حسابات.", "عند اختيار إعداد إمكانية الوصول، مثل حجم النص أو التباين العالي أو تسطير الروابط، نحفظ هذا التفضيل في التخزين المحلي للمتصفح فقط لتذكره في الزيارات اللاحقة. لا يُستخدم هذا التفضيل للإعلانات أو تتبع الزوار."] },
    { heading: "استخدام المعلومات ومشاركتها", paragraphs: ["نستخدم المعلومات للرد على الاستفسارات وتقديم الخدمات المطلوبة وإدارة التواصل التجاري وحماية الموقع والوفاء بالالتزامات القانونية. لا نبيع المعلومات الشخصية ولا نستخدمها لإعلانات غير مرتبطة بطلبكم.", "لا نشارك المعلومات إلا عند الحاجة لتقديم الخدمات أو تشغيل الموقع وحمايته أو الامتثال للقانون أو حماية حقوقنا. تخضع محادثات WhatsApp أيضاً لممارسات الخصوصية الخاصة بها."] },
    { heading: "الاحتفاظ والأمان وحذف البيانات", paragraphs: ["نحتفظ بالمعلومات للمدة اللازمة بشكل معقول أو وفقاً للقانون، ونتخذ تدابير حماية معقولة. لا توجد وسيلة نقل أو تخزين عبر الإنترنت آمنة تماماً.", `يمكنكم طلب الوصول إلى البيانات أو تصحيحها أو حذفها عبر مراسلة ${email} بعنوان طلب حذف البيانات. يرجى تضمين معلومات كافية لتحديد طلبكم. سنرد وفقاً للقانون؛ وقد نحتفظ ببعض البيانات عند السماح بذلك أو طلبه قانوناً.`] },
    { heading: "التغييرات والتواصل", paragraphs: [`قد نحدّث هذه السياسة، وستُنشر النسخة الأحدث هنا. للاستفسارات: ${email}.`] },
  ] },
  terms: { title: "شروط الاستخدام", intro: "تحكم هذه الشروط استخدامكم لموقع Web Reflect. آخر تحديث: 12 سبتمبر 2026.", backLabel: "العودة إلى Web Reflect", sections: [
    { heading: "استخدام الموقع", paragraphs: ["استخدموا الموقع لأغراض قانونية أو شخصية أو تجارية فقط. لا يجوز التدخل في تشغيله أو محاولة الوصول غير المصرح به أو إدخال رمز ضار أو استخدام محتواه بطريقة تنتهك الحقوق."] },
    { heading: "المحتوى والاستفسارات", paragraphs: ["ما لم يُذكر خلاف ذلك، فإن تصميم الموقع ونصوصه ورسوماته وشعاراته ومحتوياته الأخرى مملوكة لـ Web Reflect أو مرخّصة لها. لا يجوز نسخها أو تعديلها أو توزيعها أو استخدامها تجارياً دون إذن كتابي.", "المعلومات في الموقع عامة ولا تنشئ علاقة تعاقدية. يجب الاتفاق على الخدمات والنطاق والمواعيد والرسوم والتسليمات في اتفاق مكتوب منفصل."] },
    { heading: "الروابط الخارجية والتغييرات", paragraphs: ["خدمات الطرف الثالث، بما في ذلك WhatsApp، مستقلة عنا ولسنا مسؤولين عن محتواها أو توافرها أو خصوصيتها.", `يُقدَّم الموقع كما هو وحسب توفره. يجوز لنا تغيير هذه الشروط أو الموقع في أي وقت. الأسئلة: ${email}.`] },
  ] },
} satisfies { privacy: Document; terms: Document };

const documents = { en, he, ar };
export function getPrivacyPolicy(locale: string) { return documents[locale as keyof typeof documents]?.privacy ?? en.privacy; }
export function getTermsOfUse(locale: string) { return documents[locale as keyof typeof documents]?.terms ?? en.terms; }
